### ISSUE TITLE
Excelente implementacion y tests

### ISSUE THREAD

**Issue by semurat** [fermarja/t4_barco#1]
Muy bien dividido el problema con buen diseño y testeando cada parte.

Llegado a este punto y por aportar algo mas a la solucion, saca el terreno a una clase Tierra o Planeta o algo asi. En ese clase es donde creamos el estado incial del mismo con sus islas donde el barco puede chocar, de manera que al dar instruccines de movimiento al barco debe consultar al planeta (colaborador) si hay agua o tierra donde quiere ir para ver si se mueve o choca.

incluso mas adelante si tuvierammos mas barcos en el tablero podriamos jusgar a moverlos y ver si chocan incluso con otros barcos.

**Comment by fermarja** [comment]
Gracias

Resuelto en e39841c5c45086e53475c8de1382e6e632a7a27f
